prometheus:
  prometheusSpec:
    externalLabels: 
      cluster_name: dev-eks
    enableRemoteWriteReceiver: true
    externalUrl: "https://prometheus.azureagent.optimizor.app/"
    remoteWrite: 
    - url: https://prometheus.azureagent.optimizor.app/api/v1/write

alertmanager:
  enabled: false

grafana:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
