
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: "aws-vault-config"
spec:
  args:
    - --debug
  metadata:
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/role: "vault-role-crossplane"
      vault.hashicorp.com/agent-inject-secret-creds.txt: "secret/generic/cloud-provider/f472798f-f260-448c-b889-e6e259dc8c4f"
      vault.hashicorp.com/agent-inject-template-creds.txt: |
        {{- with secret "secret/generic/cloud-provider/f472798f-f260-448c-b889-e6e259dc8c4f" -}}
          [default]
          aws_access_key_id="{{ .Data.data.accessKey }}"
          aws_secret_access_key="{{ .Data.data.secretKey }}"
        {{- end -}}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.33.0"
  controllerConfigRef:
    name: "aws-vault-config"
