
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
name: "gcp-vault-config"
spec:
args:
  - --debug
metadata:
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "vault-role-crossplane"
    vault.hashicorp.com/agent-inject-secret-creds.txt: "secret/generic/cloud-provider/118329e4-9698-469c-b10f-40eeb6f68f16"
    vault.hashicorp.com/agent-inject-template-creds.txt: |
      {{- with secret "secret/generic/cloud-provider/118329e4-9698-469c-b10f-40eeb6f68f16" -}}
        [default]
        GOOGLE_CLOUD_KEYFILE_JSON="{{ .Data.data.keyfileJSON | toString }}"
      {{- end -}}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
name: provider-gcp
spec:
package: "xpkg.upbound.io/crossplane-contrib/provider-gcp:v0.22.0"
controllerConfigRef:
  name: "gcp-vault-config"
